export const TEAMS_FUTBOL = [
  'BOCA', 'RIVER', 'INDEPENDIENTE', 'VELEZ', 'ARGENTINOS', 'SANLORENZO', 'ESTUDIANTES', 'ALDOSIVI', 'NEWBELLS', 'DEFYJUSTICIA',
  'TALLERES', 'COLON', 'HURACAN', 'LANUS', 'GIMNASIA', 'UNION', 'BANFIELD', 'RACING', 'ROSARIOCENTRAL', 'GODOYCRUZ', 'PLATENSE',
  'CENTRALCORDOBA', 'PATRONATO', 'SARMIENTO', 'ATLETICOTUCUMAN', 'ARSENAL'
]
